apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tf-atom-acm-certificate-validation-aws
  description: "Terraform atom: AWS ACM Certificate Validation - waits for certificate DNS validation to complete"
  annotations:
    github.com/project-slug: PlatformStackPulse/tf-atom-acm-certificate-validation-aws
    backstage.io/techdocs-ref: dir:.
  tags: [terraform, aws, atom]
  links:
    - url: https://github.com/PlatformStackPulse/tf-atom-acm-certificate-validation-aws
      title: GitHub Repository
      icon: github
spec:
  type: terraform-module
  lifecycle: production
  owner: platform-team
  system: terraform-atoms
